//
// Autogenerated by Thrift Compiler (0.13.0)
//
// DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
//
import thrift = require('thrift');
import Thrift = thrift.Thrift;
import Q = thrift.Q;
import Int64 = require('node-int64');


declare enum TCompletionHintType {
  COLUMN = 0,
  TABLE = 1,
  VIEW = 2,
  SCHEMA = 3,
  CATALOG = 4,
  REPOSITORY = 5,
  FUNCTION = 6,
  KEYWORD = 7,
}

declare class TCompletionHint {
    public type: TCompletionHintType;
    public hints: string[];
    public replaced: string;

      constructor(args?: { type: TCompletionHintType; hints: string[]; replaced: string; });
  }
